# Generated by Django 5.0.6 on 2024-08-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0003_alter_cardapio_prato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='cardapio',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='estabelecimento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='pratoservido.estabelecimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(blank=True, default='logo/logopratoservido.webp', null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='ingrediente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
