# Generated by Django 5.0.6 on 2024-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0005_estabelecimento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
