# Generated by Django 5.0.6 on 2024-08-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0010_alter_estabelecimento_endereco_delete_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='proprietario',
        ),
    ]
