# Generated by Django 5.0.6 on 2024-08-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('ingrediente', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(default='prato/pratopadrao.webp', upload_to='prato')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(blank=True, default='prato/logopratoservido.webp', null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cardapio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardapio', to='pratoservido.cardapio'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='prato',
            field=models.ManyToManyField(blank=True, null=True, related_name='estabelecimento', to='pratoservido.prato'),
        ),
    ]
