# Generated by Django 5.0.6 on 2024-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0004_remove_estabelecimento_cardapio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
