# Generated by Django 5.0.6 on 2024-08-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0007_estabelecimento_email_estabelecimento_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='ingrediente',
            new_name='ingredientes',
        ),
        migrations.AddField(
            model_name='prato',
            name='estabelecimento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='pratoservido.estabelecimento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
