# Generated by Django 5.0.6 on 2024-08-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0008_rename_ingrediente_prato_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='email',
        ),
    ]
