# Generated by Django 5.0.6 on 2024-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0009_remove_estabelecimento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
