# Generated by Django 5.1.1 on 2024-10-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0014_pedido_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pratoservido.estabelecimento'),
        ),
    ]
