# Generated by Django 5.1.1 on 2024-10-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0015_pedido_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
