# Generated by Django 5.1.1 on 2024-10-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0016_pedido_bairro_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
