# Generated by Django 5.1.1 on 2024-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0017_pedido_data_entrega_pedido_data_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
