# Generated by Django 5.1.1 on 2024-10-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratoservido', '0018_pedido_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data_finalizacao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregue',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preparacao',
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('preparacao', models.BooleanField(default=False)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('entregue', models.BooleanField(default=False)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='pratoservido.pedido')),
            ],
        ),
    ]
